---
- name: Tinyproxy | Push proxy configuration to server
  ansible.builtin.template:
    src: proxy_config.j2
    dest: "{{ tinyproxy_config }}"
    mode: 0644

- name: Tinyrpoxy | Push systemd-service configuration to server
  ansible.builtin.template:
    src: tinyproxy.service.j2
    dest: "{{ tinyproxy_service_path }}"
    mode: 0644

- name: Tinyproxy | Restart systemd unit
  ansible.builtin.systemd_service:
    name: proxy.service
    enabled: true
    state: restarted
    daemon_reload: true
